import { useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, Clock3 } from "lucide-react";

import { EmptyState } from "@/components/EmptyState";
import { InlineBanner } from "@/components/InlineBanner";
import { PageSkeleton } from "@/components/PageSkeleton";
import { Button } from "@/components/ui/button";
import { ConfigureBuiltInAgentModal } from "@/components/ConfigureBuiltInAgentModal";
import { builtInAgentsApi, type BuiltInAgentState } from "@/api/builtInAgents";
import { agentsApi } from "@/api/agents";
import { queryKeys } from "@/lib/queryKeys";
import { agentUrl } from "@/lib/utils";
import { relativeTime } from "@/lib/utils";
import { useTranslation } from "@/i18n";

export interface BuiltInAgentGateProps {
  /** Registry key of the built-in agent that powers this feature (e.g. "briefs"). */
  agentKey: string;
  companyId: string | null | undefined;
  /** Human label for the gated feature. Defaults to the agent's display name. */
  featureLabel?: string;
  children: ReactNode;
}

/**
 * Wraps a feature surface that depends on a built-in agent and renders the
 * right lifecycle state (ux-spec §4):
 *
 * - loading → skeleton
 * - not_provisioned / needs_setup → setup empty-state + configure modal CTA
 * - paused → amber banner + Resume over the (stale) children
 * - ready → children
 */
export function BuiltInAgentGate({ agentKey, companyId, featureLabel, children }: BuiltInAgentGateProps) {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const [configureOpen, setConfigureOpen] = useState(false);

  const { data: states, isLoading } = useQuery({
    queryKey: queryKeys.builtInAgents.list(companyId ?? "__none__"),
    queryFn: () => builtInAgentsApi.list(companyId!),
    enabled: Boolean(companyId),
  });

  const state: BuiltInAgentState | undefined = states?.find((entry) => entry.definition.key === agentKey);

  const resume = useMutation({
    mutationFn: (agentId: string) => agentsApi.resume(agentId, companyId ?? undefined),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.builtInAgents.list(companyId ?? "__none__") });
      if (companyId) queryClient.invalidateQueries({ queryKey: queryKeys.agents.list(companyId) });
    },
  });

  // Unknown key or still resolving the company — fail open to the feature.
  if (!companyId) return <>{children}</>;
  if (isLoading && !states) return <PageSkeleton variant="detail" />;
  if (!state) return <>{children}</>;

  const label = featureLabel ?? state.definition.displayName;

  if (state.status === "not_provisioned" || state.status === "needs_setup") {
    return (
      <>
        <EmptyState
          icon={Bot}
          title={t("builtInAgentGate.setup.title", {
            defaultValue: "Set up the {{name}}",
            name: state.definition.displayName,
          })}
          message={t("builtInAgentGate.setup.message", {
            defaultValue:
              "{{label}} is generated by a built-in agent. Configure its model to enable the feature.",
            label,
          })}
          action={t("builtInAgentGate.setup.action", {
            defaultValue: "Set up {{name}}",
            name: state.definition.displayName,
          })}
          onAction={() => setConfigureOpen(true)}
          hideActionIcon
        />
        <ConfigureBuiltInAgentModal
          companyId={companyId}
          state={state}
          open={configureOpen}
          onOpenChange={setConfigureOpen}
        />
      </>
    );
  }

  if (state.status === "pending_approval") {
    return (
      <EmptyState
        icon={Clock3}
        title={t("builtInAgentGate.pendingApproval.title", {
          defaultValue: "{{name}} is pending approval",
          name: state.definition.displayName,
        })}
        message={t("builtInAgentGate.pendingApproval.message", {
          defaultValue: "{{label}} will be available after the board approves this built-in agent hire.",
          label,
        })}
      />
    );
  }

  if (state.status === "paused" && state.agent) {
    const pausedAt = state.agent.pausedAt ? relativeTime(state.agent.pausedAt) : null;
    return (
      <div className="space-y-4">
        <InlineBanner
          tone="warning"
          title={t("builtInAgentGate.paused.title", {
            defaultValue: "{{label}} is paused.",
            label,
          })}
          actions={
            <>
              <Button variant="ghost" size="sm" asChild>
                <Link to={agentUrl(state.agent)}>
                  {t("builtInAgentGate.actions.viewAgent", { defaultValue: "View agent" })}
                </Link>
              </Button>
              <Button
                size="sm"
                onClick={() => state.agent && resume.mutate(state.agent.id)}
                disabled={resume.isPending}
              >
                {resume.isPending
                  ? t("builtInAgentGate.actions.resuming", { defaultValue: "Resuming…" })
                  : t("builtInAgentGate.actions.resume", { defaultValue: "Resume agent" })}
              </Button>
            </>
          }
        >
          {t("builtInAgentGate.paused.body", {
            defaultValue: "Its built-in agent was paused{{pausedSuffix}}, so new {{label}} isn't being generated.",
            pausedSuffix: pausedAt ? ` ${pausedAt}` : "",
            label: label.toLowerCase(),
          })}
        </InlineBanner>
        {/* Paused ≠ hidden: keep existing content readable, marked stale. */}
        <div className="opacity-70">{children}</div>
      </div>
    );
  }

  return <>{children}</>;
}
